"use client";

import { useMemo, useState } from "react";
import { compact, fullDate } from "@/lib/format";
import type { DashboardData, Source } from "@/lib/types";
import { Icon } from "../icons";
import { PageHeader, SectionHeader, StatusPill } from "../dashboard";

export function DataHealthPage({ data }: { data: DashboardData }) {
  const [selected,setSelected]=useState<Source|null>(null);
  const [syncing,setSyncing]=useState(false);
  const counts=useMemo(()=>({healthy:data.sources.filter(i=>i.status==="healthy").length,warning:data.sources.filter(i=>i.status==="warning").length,stale:data.sources.filter(i=>i.status==="stale").length,rows:data.sources.reduce((s,i)=>s+i.rows,0)}),[data]);
  const sync=()=>{setSyncing(true);window.setTimeout(()=>setSyncing(false),900)};
  return <div className="page-enter">
    <PageHeader eyebrow="DATA OBSERVABILITY" title="A confiança começa antes do modelo." description="Proveniência, freshness e qualidade de cada série usada na decisão."><button className="secondary-button" onClick={sync}><Icon name="refresh" className={syncing?"spinning":""}/>{syncing?"Consultando fontes…":"Atualizar fontes"}</button></PageHeader>
    <section className="health-summary panel"><div className="health-score"><div className="score-ring"><strong>{Math.round(data.sources.reduce((s,i)=>s+i.quality,0)/data.sources.length)}</strong><span>/100</span></div><div><span>DATA TRUST SCORE</span><strong>Confiável com ressalvas</strong><small>Penalizado pela defasagem da distribuição ANP e por lags assumidos.</small></div></div><div className="health-stats"><div><i className="healthy"/><strong>{counts.healthy}</strong><span>Saudáveis</span></div><div><i className="warning"/><strong>{counts.warning}</strong><span>Atenção</span></div><div><i className="stale"/><strong>{counts.stale}</strong><span>Desatualizadas</span></div><div><Icon name="database"/><strong>{compact(counts.rows)}</strong><span>Observações</span></div></div></section>
    <section className="panel section-gap"><SectionHeader title="Catálogo de fontes" subtitle="Clique em uma linha para inspecionar proveniência e alertas"/><div className="source-table"><div className="source-head"><span>Fonte</span><span>Status</span><span>Cobertura</span><span>Último dado</span><span>Qualidade</span><span/></div>{data.sources.map(source=><button className="source-row" key={source.id} onClick={()=>setSelected(source)}><div><span className={`source-logo ${source.status}`}>{source.institution.slice(0,3).toUpperCase()}</span><span><strong>{source.name}</strong><small>{source.institution} · {source.frequency} · {source.unit}</small></span></div><StatusPill status={source.status}/><span>{source.coverage}</span><span>{fullDate(source.latest)}</span><div className="quality-bar"><i><b style={{width:`${source.quality}%`}}/></i><strong>{source.quality}</strong></div><Icon name="chevron" size={16}/></button>)}</div></section>
    <section className="two-col section-gap">
      <div className="panel checks-panel"><SectionHeader title="Quality gates" subtitle="Checks executados antes de treinar e publicar"/><div className="check-list">{data.qualityChecks.map(check=><div key={check.name} className={check.status}><span><Icon name={check.status==="pass"?"check":"warning"}/></span><div><strong>{check.name}</strong><small>{check.detail}</small></div><em>{check.status==="pass"?"PASS":check.status==="warning"?"REVIEW":"FAIL"}</em></div>)}</div></div>
      <div className="panel lineage-panel"><SectionHeader title="Lineage do target" subtitle="ANP Diesel S10 — Brasil"/><div className="lineage-flow"><Lineage step="01" title="Raw" sub="CSV ANP + snapshots" meta="426.047 registros S10"/><Lineage step="02" title="Normalizado" sub="posto-dia · BRL/L" meta="407.496 posto-dias"/><Lineage step="03" title="Silver" sub="agregação W-SUN" meta="136 semanas completas"/><Lineage step="04" title="Snapshot causal" sub="horário exato quando disponível" meta="fallback conservador de +8 dias"/><Lineage step="05" title="Gold" sub="features e forecasts" meta="corte em 09/08/2026"/></div></div>
    </section>
    {selected&&<div className="drawer-backdrop" onClick={()=>setSelected(null)}><aside className="source-drawer" onClick={event=>event.stopPropagation()}><button className="drawer-close" onClick={()=>setSelected(null)}><Icon name="x"/></button><span className={`source-logo large ${selected.status}`}>{selected.institution.slice(0,3).toUpperCase()}</span><span className="eyebrow">SOURCE PROFILE</span><h2>{selected.name}</h2><p>{selected.institution}</p><StatusPill status={selected.status}/><div className="drawer-fields"><div><span>Observações</span><strong>{selected.rows.toLocaleString("pt-BR")}</strong></div><div><span>Cobertura</span><strong>{selected.coverage}</strong></div><div><span>Último dado</span><strong>{fullDate(selected.latest)}</strong></div><div><span>Publication lag</span><strong>{selected.lag}</strong></div><div><span>Unidade</span><strong>{selected.unit}</strong></div><div><span>Frequência</span><strong>{selected.frequency}</strong></div></div><div className="quality-large"><span>QUALITY SCORE</span><strong>{selected.quality}/100</strong><i><b style={{width:`${selected.quality}%`}}/></i></div>{selected.warning&&<div className="source-warning"><Icon name="warning"/><p>{selected.warning}</p></div>}<div className="method-note"><Icon name="shield"/><p>O status da fonte participa do cálculo de confiança operacional e pode ampliar o intervalo preditivo.</p></div></aside></div>}
  </div>;
}
function Lineage({step,title,sub,meta}:{step:string;title:string;sub:string;meta:string}){return <div className="lineage-item"><b>{step}</b><div><strong>{title}</strong><span>{sub}</span><small>{meta}</small></div></div>}
